//#define MAIN_GUI
//#define MAIN_FEMMESH
//#define MAIN_FULLSPACE_BEAM
//#define MAIN_REDUCED_BEAM
//#define MAIN_LOCAL_BASIS
//#define MAIN_DFO_REDUCED_BEAM
//#define MAIN_RS_REDUCED_BEAM
//#define MAIN_FILE_FORMAT
//#define MAIN_LMA_BASIS
//#define MAIN_CUBATURE
#define MAIN_TEST_DINO
//#define MAIN_TEST_LOAD_GEOM
